### ISSUE TITLE
mcp1525 pin numbering

### ISSUE THREAD

**Issue by alpinekid** [KiCad/kicad-symbols#1037]
In library: **Reference_voltage**
part MCP1525-TO; alias MCP1541-TO has a bad pin out.
There is a difference between the to-92 package and the sot-23-3 package.
The manufacture reversed the usage of pin numbers:-(

for the to-92 package,
Vss and Vin have been swapped between the to-92 and the sot.
Vss should be on pin 1, its the ground pin, on the to-92 
Vin should be on pin 3, its the supply voltage.

Its the reverse from the surface mount version of this part so it was an easy miss.
The mcp1541-TT is correct for surface mount package.
The mcp1541-TO symbol has the wrong pin outs.

The mfg part number difference is: through hole mcp1541 and surface mount is mcp1541T.
Its the suffix T that is important.

NB: its not a footprint issue, the pin number definition change between packages.

data sheet http://ww1.microchip.com/downloads/en/DeviceDoc/21653C.pdf

I know this because I just let the smoke out of a part.

**Comment by evanshultz** [comment]
Pardon me for any rehashing, but let me dump all information I reviewed into this comment for verification.

Datasheet pinouts:
![image](https://user-images.githubusercontent.com/1936989/46573841-74901880-c94f-11e8-952b-d4f1d9d1c674.png)

Indeed, I see the symbols for each package have the same pin order:
![image](https://user-images.githubusercontent.com/1936989/46573864-a73a1100-c94f-11e8-926e-3d9a938b5e39.png)

Since the footprint pinout could vary, let's confirm that too.

SOT-23:
![image](https://user-images.githubusercontent.com/1936989/46573855-96899b00-c94f-11e8-834f-a144035c3bba.png)

TO-92_Inline:
![image](https://user-images.githubusercontent.com/1936989/46573874-c8026680-c94f-11e8-8da8-23e1d38b95da.png)

Yep, the TO92 symbol needs pins1 and 3 reversed. I'm sorry that this error exists in the library and that it gave you a nasty surprise. However, thanks for the patience to report it.

Are you willing to submit a PR to fix the TO92 symbol's pinout?

**Comment by evanshultz** [comment]
Fix submitted at https://github.com/KiCad/kicad-symbols/pull/1044.

**Comment by poeschlr** [comment]
Fix merged
