### ISSUE TITLE
Was there a reason for removing the 3.3V version of the LEM HO-8 (and its sisters)

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#1170]
I seem to remember that we had the 3.3 versions of these in our lib. (I have been the one adding it a while back) But i can no longer find them. Where they removed for some good reason on accident or am i just blind?

For reference we now have LEM_HO8-NP but not LEM_HO8-NP/SP33 (The / in the part number would need to be replaced by some other character) Both can reference the same footprint but would need a different datsheet link.

The same applies to the 15A and 25A variants.

**Comment by antoniovazquezblanco** [comment]
This happened in https://github.com/KiCad/kicad-symbols/pull/700/files.

Maybe it was accidental?

**Comment by evanshultz** [comment]
You're talking about https://www.lem.com/sites/default/files/products_datasheets/ho-np-0000_series.pdf and https://www.lem.com/sites/default/files/products_datasheets/ho-np_sp33-1000_series.pdf? I don't mind any symbols with "SP33" in their name and the "HO8" ones in the lib now specifically mention a 5V rail. I probably missed the unique datasheets and voltages in an attempt to simplify and reconcile things.

I'll add the accidentally removed symbols since this was my fault. If you have a list of them that would be faster than me searching by myself, but if you give me a few days I'll figure it out.

**Comment by evanshultz** [comment]
PR submitted at https://github.com/KiCad/kicad-symbols/pull/1188 to add back in the 8A, 15A, and 25A symbols. Are there others? I marked it for inclusion in 5.0.2 since it's a regression.
