### ISSUE TITLE
State of the lib regarding 5.0.2

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#1213]
What is the state regarding the 5.0.2 release? Is there anything still to do? (Otherwise i will tag tomorrow morning before i go to work. So about 06:45 central european winter time.)

---

Report by the "check for design breaking changes" script:

Pins have been moved, renumbered or removed in symbols:
- '4xxx_IEEE.lib:4067' (bugfix)
- '4xxx_IEEE.lib:4508' (bugfix)
- 'Analog_ADC.lib:ADC1173' (false positive)
- 'Connector.lib:AudioJack2_Ground_Switch' (ground pin added to fit the symbol name)
- 'Connector.lib:AudioJack3_Ground_Switch' (ground pin added to fit the symbol name)
- 'Connector.lib:XLR3_AudioJack2_Combo_Ground' (ground pin added to fit the symbol name)
- 'Connector.lib:XLR3_AudioJack3_Combo_Ground' (ground pin added to fit the symbol name)
- 'Converter_ACDC.lib:VTX-214-015-103' (bugfix, clarification from manufacturer)
- 'Power_Management.lib:BTS40K2-1EJC'
- 'Power_Management.lib:BTS50055-1TMA'
- 'Power_Management.lib:BTS50080-1TEA'

Normal pins ok but NC pins have been moved, renumbered or removed in symbols: 
- 'Interface_Ethernet.lib:KSZ9031RNXCA'

Full report: [report.txt](https://github.com/KiCad/kicad-symbols/files/2641165/report.txt)

**Comment by antoniovazquezblanco** [comment]
4xxx_IEEE were bugfixes as stated by you. See https://github.com/KiCad/kicad-symbols/pull/1159 for more details.

Analog ADC is reported as moved because pin length was fixed to 100mil to comply with KLC but it does not break compatibility. See https://github.com/KiCad/kicad-symbols/pull/1167 for more details

Converter_ACDC.lib:VTX-214-015-103 I am responsible for that one. Vigortronix clarified that the FG pin in that model is actually a NC so we hided it and moved it out of the way. See https://github.com/KiCad/kicad-symbols/pull/1140 for more details.

Power management stuff comes from https://github.com/KiCad/kicad-symbols/pull/572 which I had no time to follow. There is a following PR that we may want to have a look at https://github.com/KiCad/kicad-symbols/pull/1051.

**Comment by antoniovazquezblanco** [comment]
Can this be closed?
