### ISSUE TITLE
C64AB symbol has inconsistent pin names and pin numbers

### ISSUE THREAD

**Issue by sxpert** [KiCad/kicad-symbols#1678]

**Comment by evanshultz** [comment]
Thanks for taking the time to report an issue you found with the official libraries.

I'm closing this because it's a known issues that's been brought up before. Please try searching in the future before making a new issue.

All DIN 41612 symbols and footprints are planned to be updated, and a whole range of scripted footprints is moving along but didn't make it into v5.1.
