### ISSUE TITLE
APA102 Footprint incorrect

### ISSUE THREAD

**Issue by wirehead** [KiCad/kicad-symbols#1910]
I printed out a PCB that used the APA102 symbol provided in the built-in library and was validating all of the footprints against the printout.

Pictured, a bit hard to see, is an APA102 using the library's footprint. You can see that the spacing on the pads doesn't match.

![image](https://user-images.githubusercontent.com/653135/59154192-c24eaa80-8a21-11e9-9611-83f7a0ead49d.png)

[The SparkFun library](https://github.com/sparkfun/SparkFun-KiCad-Libraries) seems to be correct when I checked it physically against the part.

**Comment by poeschlr** [comment]
please post a link to the datasheet

**Comment by wirehead** [comment]
That's the APA102-2020 you linked to.  This concerns the APA102 which uses the LED_RGB_PLCC-6 footprint.

Here's a datasheet: http://www.led-color.com/upload/201506/APA102%20LED.pdf

**Comment by poeschlr** [comment]
Your datasheet does not contain a dimensioned drawing. It is therefore useless to determine which footprint should be used

**Comment by evanshultz** [comment]
Perhaps I can add a bit more info to clarify...

The APA102-2020 symbol references an atomic and, I hope, correct footprint:
![image](https://user-images.githubusercontent.com/1936989/59223867-d90c1300-8b81-11e9-934e-929eb17ae2f3.png)

But the APA102 symbol uses a more generic footprint:
![image](https://user-images.githubusercontent.com/1936989/59223909-f214c400-8b81-11e9-8be0-1d41bcbdde67.png)

The product page for APA102 appears to be at http://szledcolor.com/productshow.asp?id=878&sid=199, but it is the datasheet you linked above without dimensions. It appears you have found an error in the library but we can't take any action to correct it right now because we're missing the information to tell us what the correct footprint should be.

If you can identify the correct package and/or footprint information, would you be willing to submit a footprint for this part and also update the symbol to use that footprint?

**Comment by fauxpark** [comment]
Per #1501 it seems the footprints for both are correct. The submitter links to an Adafruit datasheet, containing the same drawing, and says it is PLCC-6 (5050) - which is exactly what the part in the OP here is.

I think the main problem is that while the 2020 symbol has the `-2020` suffix, the 5050 symbol has no suffix at all.

**Comment by wirehead** [comment]
No, unfortunately, I think you underestimate just how annoying the modern SMT LED industry has become.  Like, sure, fiat lux, but can we fiat lux in a discrete number of packages instead of ten zillion almost-but-not-quite-identical packages, none of them with standardized descriptive names?

So, I found this discussion from the forums: https://forum.kicad.info/t/smd-rgb-led-footprint-5050/653/8 and the associated PR from two years ago.

I just did my check and if the APA102 uses the `LED_SMD:LED_RGB_5050-6` footprint instead of the `LED_SMD:LED_RGB_PLCC-6` footprint, it fits.  So I think this problem is easily solved just by changing footprints.

Also, yeah, it's probably proper and least-surprise to call it a `APA102-5050` as compared to a `APA102-2020`.

**Comment by fauxpark** [comment]
Ah, I was under the impression the PLCC-6 footprint was 5050... it is actually 3434.

**Comment by poeschlr** [comment]
The APA102-2020 is called that by the manufacturer this is why this name is used. The datasheets linked here call the part APA102C which would be the proper name of it.

**Comment by evanshultz** [comment]
@wirehead 
If you can submit a PR to change the symbol to use a correct footprint, since things are broken, we will accept that right away.

But I still haven't seen a datasheet that shows dimensions so we can verify that the `LED_RGB_5050-6` footprint is correct. Are you able to find some documentation?

**Comment by evanshultz** [comment]
@wirehead 
It seems like the issue is sorted out above. Are you willing to make a PR to fix this? Would be nice to squeeze it into 5.1.3 which is coming soon.

**Comment by evanshultz** [comment]
I contacted the vendor to request a footprint or an adequately-dimensioned package drawing for APA102.

**Comment by evanshultz** [comment]
No answer after multiple inquires. I'm giving up.

Is the expectation that changing the footprint for this symbol to `https://github.com/KiCad/kicad-footprints/blob/master/LED_SMD.pretty/LED_RGB_5050-6.kicad_mod` will fix the issue?

**Comment by wirehead** [comment]
PR submitted.  Very sorry for going silent on this.
