### ISSUE TITLE
LF398_xxx:  8pin and 14pin  pinnings swapped

### ISSUE THREAD

**Issue by elektrouwe** [KiCad/kicad-symbols#2097]
14pin version uses 8pin enumeration and 8pin versions use 14pin enumeration

**Comment by evanshultz** [comment]
It's not entirely clear from about what you mean. There is only one 14-pin LF398 symbol, but there are three 8-pin symbols (though only two have an underscore suffix). Let's dig into it.

Datasheets:
- http://www.ti.com/lit/ds/symlink/lf398-n.pdf (all but SOIC 8)
- https://www.analog.com/media/en/technical-documentation/data-sheets/lt0398s8.pdf (SOIC 8)

We have see that all 8-pin symbols share a common pinout, so that makes life easier.

After reviewing the symbols:
1. `LF398H` has a correct pin, so that one is fine. And it's not included above because of the underscore, but I wanted to check anyway.
1. `LF398_DIP8` does use the SOIC 14 pinout. So that's wrong.
1. LF398_SOIC14` uses the 8-pin pinout, so that's wrong as well.

@elektrouwe 
Confirmed problem. Thank you for noticing this and taking the time to report it. Sorry it's wrong.
