### ISSUE TITLE
Commit own symbols / footprint / packages

### ISSUE THREAD

**Issue by silelis** [KiCad/kicad-symbols#2145]
Hello,

I am just starting with KiCAD (switching from Eagle2KiCAD) but have some amount of symbols / footprint / packages like Bluetooth, FM, DAB+ breakouts, mp3 chips (like au6850) and other.

My question is how and if I can share it with this git? I don't want to loose theme and can share with community

**Comment by antoniovazquezblanco** [comment]
Yes! Your contributions are very welcomed!

You have brief instructions in http://kicad-pcb.org/libraries/contribute/ on how to proceed.

Thank you!

**Comment by evanshultz** [comment]
@silelis 
Welcome!

Note that there are guidelines for this library at http://kicad-pcb.org/libraries/klc/ which contributions need to adhere to. Your symbols/footprints may need updating before they can be included in the library here.

Since I hope your question is answered please close this issue when you have a chance. Or if not, add another comment.

**Comment by DanSGiesbrecht** [comment]
Unless anyone has an objection, I'm going to close this.
