### ISSUE TITLE
MCP1623

### ISSUE THREAD

**Issue by jneiva08** [KiCad/kicad-symbols#2574]
Hi,

I wish to add MCP1623/4, have found the MCP1640 is identical.
Should add new symbol or only add as aliases?

Thanks

**Comment by aris-kimi** [comment]
Hi @jneiva08 it would be better to add this as an allias but with a clear description, similar to the parent item, in order to display differences.. It would be great to correct parent's item and others' aliases' description by adding the frequency as it is show at MCP1650.

But you better wait for someone else to advise further...

**Comment by cpresser** [comment]
I gave it a quick look and can confirm that @aris-kimi is right.
The Pins and package-configuration matches, so an alias is the way to go.
