### ISSUE TITLE
74LS09 outputs not open collector

### ISSUE THREAD

**Issue by StormTrooper** [KiCad/kicad-symbols#2740]
The output of 74LS09 should be  open collector as per the datasheet.

https://www.ti.com/lit/ds/symlink/sn74ls06.pdf

In the symbols library the 4 outputs are not set to open collector.
![properties](https://user-images.githubusercontent.com/1429043/82154964-5ac3f080-9869-11ea-989f-0502be477538.png)

![output](https://user-images.githubusercontent.com/1429043/82154977-7b8c4600-9869-11ea-8410-99fc253b2536.png)

**Comment by evanshultz** [comment]
Confirmed.

'LS08 is the symbol and it does have push-pull outputs. So that's fine. See https://www.ti.com/lit/ds/symlink/sn74ls08.pdf?&ts=1589781457949.

But 'LS09 is an ALIAS to 'LS08 but it shouldn't be because it does have open-collector outputs. See http://www.ti.com/lit/ds/symlink/sn74ls09.pdf?&ts=1589781485392.

The solution is to copy the 'LS08 symbol, rename it so 'LS09, change the output pin types, and then delete the ALIAS from 'LS08. @StormTrooper Are you willing and able to submit a PR?
