### ISSUE TITLE
Generic symbol for BOM elements that do not have a footprint

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-symbols#380]
I have some elements that I want to include in my schematic and BOM but that do not have a footprint. One example may be FPC cables or RF antenas or even a case for a PCB.

I am wondering if there is a generic component in KiCad libraries that can be used for this purpose or if should be added to the libraries in case it doesn't exist.

**Comment by jkriege2** [comment]
I think you could simply create a symbol for that and leave the footprint field empty/don't assign it? Then it wuld appear in a BOM exported from the eschmatic editor, but not in the BOM exported from the PCB-Editor.

Another option would be (I think) to generate an empty footprint (set the virtual flag!), which may even contain a bit of drawing on the silkscreen to show where to e.g. connect cables ... Such a footprint will appear in the BOM exported from the PCB-Editor, but (due to the virtual flag) not in the footprint-Position (i.e. autoplacement) file.

Does that help?

**Comment by jkriege2** [comment]
additionally: If you don't assign a footprint, you'll se an error when importing the netlist in the PCB-Editor ... so maybe the empty footprint is an option? You could even hide it completely ... but I haven't tested what the effects of such a footprint would be ...

**Comment by jkriege2** [comment]
@evanshultz @poeschlr @Misca1234 @Ratfink  Any input on this? Should we add such an invisible "empty" symbol, so people can use it that way (but it seems a bit of a hack to me)?

**Comment by antoniovazquezblanco** [comment]
I think this element can be rather useful and would simplify my job whenever I have to order something after having updated my board as I would not need to touch the final BOM to add those components that my manufacturer will source for me.

**Comment by Ratfink** [comment]
Philosophically, I don't know why things that aren't part of the PCB should be on the PCB's schematic.  An extra tool for better BOM management beyond the schematic would be good to have, but a hack to do it via fake symbols on the schematic just feels wrong to include in the standard library.

**Comment by antoniovazquezblanco** [comment]
I agree with you @Ratfink in the sense that this is a hack.

For me, this solution is easy as I have one single supplier that provides all the parts. What tools do you use to manage this?

**Comment by evanshultz** [comment]
I think this is a question for the devs, since I believe KiCad has no support for this and it seems like nobody above is aware of it either. It is a very reasonable request for KiCad to support adding BOM elements that aren't a "normal" ECAD component. I, for one, would be delighted to see any ECAD tool have a nice implementation of this concept.

You may also ask the KiCad user forum instead, where you may find a bigger audience.

I've only seen poor support for this concept in other ECAD tools, but many products I've worked on needed parts in the BOM that didn't have a schematic symbol and/or footprint. Like the examples mentioned above and also spacers under TO92s, wire guides around ribbon cables, etc. Those items belong on the BOM for a PCBA but it's always been a hacky experience to add them when I've tried, and sometimes it wasn't possible or it was easier to track them outside of the ECAD design.

Personally, I would be leery of putting oddball stuff that is corporation- or user-specific in to the official libs. Especially if it was hacky.

@Ratfink One good thing about a schematic symbol for a part like this is that a PDF and/or printout shows these elements, so somebody in doc control or manufacturing that isn't technical can check that the parts are included. When documents are checked for release not everybody needs to know how to use an ECAD tool. Or if some mechanical part is found to be missing on a PCBA then the schematic will show if the mechanical part should have been there.

**Comment by antoniovazquezblanco** [comment]
https://forum.kicad.info/t/generic-symbol-for-bom-elements/9996

**Comment by antoniovazquezblanco** [comment]
I believe there has not been enough aceptance among users to consider this a desirable feature. Many alternatives have been proposed in the forums.

Thank you very much!
