### ISSUE TITLE
Inconsistency in AudioJack_Switch symbols

### ISSUE THREAD

**Issue by Ratfink** [KiCad/kicad-symbols#635]
I believe all the switched pins in our audio jack symbols are supposed to disconnect when a plug is inserted.  That's the way that AudioJack3_Switch is drawn:
![screenshot from 2018-05-29 11-54-17](https://user-images.githubusercontent.com/320472/40670588-b15d2fd8-6337-11e8-9f4a-4ffcf74894b2.png)
But AudioJack3_Ground_Switch is drawn depicting switches that would close when a plug is inserted:
![screenshot from 2018-05-29 11-54-13](https://user-images.githubusercontent.com/320472/40670622-bfe99532-6337-11e8-86b0-a5ca9284d38b.png)
I believe this is a bug in AudioJack3_Ground_Switch, so we really should fix it.  It might also be nice to rearrange the pins to match AudioJack3_Switch's ordering.

**Comment by evanshultz** [comment]
When the symbols were merged at https://github.com/KiCad/kicad-symbols/pull/310#issuecomment-379877419 I was soliciting feedback on these symbols because I think they can be improved as well, although I hadn't brought up this specific item, but that PR didn't need to get any more changes. I drew the upper symbol you show and retained the lower one since it could have been included in legacy schematics that would break connections, but I'm still OK changing it. With the nice assortment of audio jack symbols now in the lib I support a bit of polish and consistency for these symbols.

**Comment by Ratfink** [comment]
Sure could! 🙂

**Comment by evanshultz** [comment]
PR submitted at https://github.com/KiCad/kicad-symbols/pull/714.
