### ISSUE TITLE
Isolated Resistor Network

### ISSUE THREAD

**Issue by leoheck** [KiCad/kicad-symbols#809]
I don't have this kind of part on my lib. It will be nice to add it.

![image](https://user-images.githubusercontent.com/1277920/43920104-5e450984-9bee-11e8-9f3c-30ff9f50b9e4.png)

Something like this!

![image](https://user-images.githubusercontent.com/1277920/43920156-81f4aefc-9bee-11e8-9265-7e76c25074a5.png)

**Comment by evanshultz** [comment]
They already exist in the HEAD rev of the library at https://github.com/KiCad/kicad-symbols/blob/master/Device.lib:
![image](https://user-images.githubusercontent.com/1936989/43924719-301ad41c-9bda-11e8-99d9-bf27e4024812.png)

We don't take requests here so I'll leave this open for a couple days before closing it. We do, however, welcome submissions. There are plenty of symbols that could be added so if you want to submit a PR instead of a request that would be great.

**Comment by Ratfink** [comment]
Evan got in before me and covered most of what I was going to say.  However, I have one more observation:

One thing we should do here is add the keyword "isolated" to those symbols, since that does seem to be something manufacturers use to refer to these ([Bourns](https://www.bourns.com/pdfs/4100R.pdf), [Vishay](http://www.vishay.com/docs/31511/31511.pdf)).  I'll submit a PR for that shortly.

**Comment by leoheck** [comment]
@evanshultz thanks to show me that. @Ratfink that is a good thing too. The image I added here on my first post is from a datasheet and has the `isolated` keyword.
