### ISSUE TITLE
Missing symbols for magnetic sensors and number of other libraries

### ISSUE THREAD

**Issue by YordanYanakiev** [KiCad/kicad-symbols#872]
Hello.
There is missing 3D/footprints for some libraries in 5.x.

**Comment by antoniovazquezblanco** [comment]
Ping @YordanYanakiev. Please, could you answer the questions above?

**Comment by antoniovazquezblanco** [comment]
@YordanYanakiev ping!

**Comment by evanshultz** [comment]
Just to try and wrap this up...

I don't think it's about schematic symbols (as originally reported) because https://github.com/KiCad/kicad-library/pull/1697/files are the file changes for an attempt to split up the sensor libs in the old library. Comparing with the current lib at https://github.com/KiCad/kicad-symbols/blob/master/Sensor_Magnetic.dcm, all old symbols are there.

If about footprints, while it's true that https://github.com/KiCad/kicad-footprints does not have a Sensor_Magnetic repo, all symbols in the current Sensor_Magnetic symbol library are associated with generic footprints that do exist in our footprint library.

So I don't see an issue with magnetic sensors at all and any other real issue can be surfaced later.
